### PR TITLE
Added the basic skeleton

### PR DESCRIPTION
**Pull request by devang-gaur**

### CODE REVIEW

**Comment by mik-dass** [comment]
LGTM

**Review by anmolbabu — APPROVED** [review]
LGTM
Verified?

**Comment by devang-gaur** [comment]
On minishift ? I just ran all the npm commands and all was clean.

**Comment by anmolbabu** [comment]
@dev-gaur npm commands helps you know if the app runs as expected or run tests on app or even check linter aspects but you would also need to test running the cico* scripts

**Pull request merged**
